Train_transform_list:
  Resize:
      size: [352, 352]
  RandomScaleCrop:
      range: [0.75, 1.25]
  RandomFlip:
      lr: True
      ud: True
  RandomRotate:
      range: [0, 359]
  random_image_enhance:
      methods: ['contrast', 'sharpness', 'brightness']
  random_dilation_erosion:
      kernel_range: [2, 5]
  tonumpy: NULL
  normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  totensor: NULL